import json
import os
import sqlite3
import uuid
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

import psycopg
from psycopg import errors as pg_errors

from pipeline.db import url_hash  # R5: боевая формула дедупа (D19)

from . import config

# SQL в коде — на диалекте Postgres (%s, ON CONFLICT, RETURNING); для sqlite
# _SqliteConn переписывает %s → ? (М2: движок выбирается по env, см. connect).

# Схема — docs/plan.md §1.2 + П.2 (правки после сверки)
SCHEMA_SQLITE = """
CREATE TABLE IF NOT EXISTS users (
  chat_id      INTEGER PRIMARY KEY,
  tz_offset_min INTEGER NOT NULL DEFAULT 180,
  send_times   TEXT NOT NULL DEFAULT '["09:00"]',
  last_sent_at TEXT,
  created_at   TEXT NOT NULL,
  onboarded_at TEXT
);
CREATE TABLE IF NOT EXISTS sources (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id    INTEGER NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  kind       TEXT NOT NULL CHECK (kind IN ('rss','html','tgweb','reddit','twitter')),
  url        TEXT NOT NULL,
  title      TEXT NOT NULL,
  topics     TEXT NOT NULL DEFAULT '[]',
  origin     TEXT NOT NULL DEFAULT 'survey' CHECK (origin IN ('survey','manual')),
  enabled    INTEGER NOT NULL DEFAULT 1,
  status     TEXT NOT NULL DEFAULT 'ok' CHECK (status IN ('ok','degraded','error')),
  status_msg TEXT,
  last_post_id INTEGER NOT NULL DEFAULT 0,
  added_at   TEXT NOT NULL,
  UNIQUE (chat_id, kind, url)
);
CREATE INDEX IF NOT EXISTS idx_sources_chat ON sources (chat_id, enabled);
CREATE TABLE IF NOT EXISTS items (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  source_id    INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  url          TEXT NOT NULL,
  title        TEXT NOT NULL,
  published    TEXT NOT NULL,
  fetched_at   TEXT NOT NULL,
  url_hash     TEXT NOT NULL,
  UNIQUE (source_id, url_hash)
);
CREATE INDEX IF NOT EXISTS idx_items_published ON items (published);
CREATE TABLE IF NOT EXISTS digests (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id      INTEGER NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  period_from  TEXT NOT NULL,
  period_to    TEXT NOT NULL,
  item_count   INTEGER NOT NULL,
  message_text TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_digests_chat ON digests (chat_id, created_at);
CREATE TABLE IF NOT EXISTS digest_items (
  digest_id INTEGER NOT NULL REFERENCES digests(id) ON DELETE CASCADE,
  item_id   INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  PRIMARY KEY (digest_id, item_id)
);
CREATE TABLE IF NOT EXISTS chat_history (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id    INTEGER NOT NULL,
  role       TEXT NOT NULL,
  text       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS fsm (
  key        TEXT PRIMARY KEY,
  state      TEXT,
  data       TEXT,
  updated_at TEXT NOT NULL
);
"""

# PG-вариант: AUTOINCREMENT → IDENTITY, datetime('now') → to_char(now()) ISO Z.
SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS users (
  chat_id      INTEGER PRIMARY KEY,
  tz_offset_min INTEGER NOT NULL DEFAULT 180,
  send_times   TEXT NOT NULL DEFAULT '["09:00"]',
  last_sent_at TEXT,
  created_at   TEXT NOT NULL,
  onboarded_at TEXT
);
CREATE TABLE IF NOT EXISTS sources (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id    INTEGER NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  kind       TEXT NOT NULL CHECK (kind IN ('rss','html','tgweb','reddit','twitter')),
  url        TEXT NOT NULL,
  title      TEXT NOT NULL,
  topics     TEXT NOT NULL DEFAULT '[]',
  origin     TEXT NOT NULL DEFAULT 'survey' CHECK (origin IN ('survey','manual')),
  enabled    INTEGER NOT NULL DEFAULT 1,
  status     TEXT NOT NULL DEFAULT 'ok' CHECK (status IN ('ok','degraded','error')),
  status_msg TEXT,
  last_post_id INTEGER NOT NULL DEFAULT 0,
  added_at   TEXT NOT NULL,
  UNIQUE (chat_id, kind, url)
);
CREATE INDEX IF NOT EXISTS idx_sources_chat ON sources (chat_id, enabled);
CREATE TABLE IF NOT EXISTS items (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id    INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  url          TEXT NOT NULL,
  title        TEXT NOT NULL,
  published    TEXT NOT NULL,
  fetched_at   TEXT NOT NULL,
  url_hash     TEXT NOT NULL,
  UNIQUE (source_id, url_hash)
);
CREATE INDEX IF NOT EXISTS idx_items_published ON items (published);
CREATE TABLE IF NOT EXISTS digests (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id      INTEGER NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE,
  period_from  TEXT NOT NULL,
  period_to    TEXT NOT NULL,
  item_count   INTEGER NOT NULL,
  message_text TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_digests_chat ON digests (chat_id, created_at);
CREATE TABLE IF NOT EXISTS digest_items (
  digest_id INTEGER NOT NULL REFERENCES digests(id) ON DELETE CASCADE,
  item_id   INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  PRIMARY KEY (digest_id, item_id)
);
CREATE TABLE IF NOT EXISTS chat_history (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id    INTEGER NOT NULL,
  role       TEXT NOT NULL,
  text       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC',
                                            'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
CREATE TABLE IF NOT EXISTS fsm (
  key        TEXT PRIMARY KEY,
  state      TEXT,
  data       TEXT,
  updated_at TEXT NOT NULL
);
"""


class _Row(dict):
    """Строка результата: и row["col"], и row[0] (замена sqlite3.Row)."""

    def __init__(self, cols, values):
        super().__init__(zip(cols, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)

    def __iter__(self):  # tuple-распаковка: for _id, title, ... in rows
        return iter(self._values)


def _pg_row_factory(cursor):
    if cursor.description is None:  # INSERT/UPDATE/DDL без RETURNING
        return lambda values: None
    cols = [d.name for d in cursor.description]

    def make(values):
        return _Row(cols, values)

    return make


class _SqliteCursor:
    def __init__(self, cur):
        self._c = cur

    def execute(self, sql, params=()):
        return self._c.execute(sql.replace("%s", "?"), params)

    def executemany(self, sql, seq):
        return self._c.executemany(sql.replace("%s", "?"), seq)

    def __getattr__(self, name):
        return getattr(self._c, name)


class _SqliteConn:
    """sqlite3-коннект в PG-диалекте: %s → ?, transaction() как у psycopg."""

    def __init__(self, conn):
        self._c = conn

    def execute(self, sql, params=()):
        return self._c.execute(sql.replace("%s", "?"), params)

    def executemany(self, sql, seq):
        return self._c.executemany(sql.replace("%s", "?"), seq)

    def cursor(self):
        return _SqliteCursor(self._c.cursor())

    def commit(self):
        return self._c.commit()

    def rollback(self):
        return self._c.rollback()

    def close(self):
        return self._c.close()

    @contextmanager
    def transaction(self):
        with self._c:  # sqlite3: успех → commit, исключение → rollback
            yield

    def __getattr__(self, name):
        return getattr(self._c, name)


def executemany(conn, sql, seq):
    """psycopg3 держит executemany на курсоре; sqlite — на коннекте."""
    return conn.cursor().executemany(sql, seq)


def _pg_connect(url):
    # autocommit: как sqlite с явными commit() — проще всего перенести логику;
    # prepare_threshold=None — никаких prepared statements (pgbouncer transaction
    # mode не гарантирует их между транзакциями; 0 означало бы «готовить всегда»).
    conn = psycopg.connect(url, row_factory=_pg_row_factory, autocommit=True)
    conn.prepare_threshold = None
    return conn


def _run_schema(conn, schema):
    for stmt in schema.split(";"):
        if stmt.strip():
            conn.execute(stmt)


def connect(path=None):
    """Выбор движка: BOT_DB_PATH/файл → sqlite; SUPABASE_DB_URL → PG;
    ':memory:' (тесты) → PG во временной схеме, если задан BOT_TEST_PG_URL."""
    if path == ":memory:" and config.TEST_PG_URL:
        conn = _pg_connect(config.TEST_PG_URL)
        schema = f"t_{uuid.uuid4().hex}"
        conn.execute(f'CREATE SCHEMA "{schema}"')
        conn.execute(f'SET search_path TO "{schema}"')
        _run_schema(conn, SCHEMA_PG)
        return conn
    if path is None and config.SUPABASE_DB_URL and not os.environ.get("BOT_DB_PATH"):
        conn = _pg_connect(config.SUPABASE_DB_URL)
        _run_schema(conn, SCHEMA_PG)
        return conn
    # check_same_thread=False: хендлеры зовут БД через asyncio.to_thread (последовательно)
    conn = sqlite3.connect(path or config.DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(SCHEMA_SQLITE)
    return _SqliteConn(conn)


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def is_broken(conn) -> bool:
    """Мёртвое соединение (М2: PG-коннект к Supabase после обрыва сети
    вечно отдаёт «another command is already in progress» — инцидент
    2026-09-14). sqlite — файл на диске, ломаться нечему."""
    if conn is None or isinstance(conn, _SqliteConn):
        return False
    try:
        conn.execute("SELECT 1").fetchone()
        return False
    except Exception:
        return True


def reconnect(conn):
    """Битое PG-соединение → свежее (вызывает slots_loop при сбое тика).
    Не бросает: если сеть ещё недоступна, вернёт старое — повтор на
    следующем тике (20 с)."""
    if not is_broken(conn):
        return conn
    try:
        conn.close()
    except Exception:
        pass
    try:
        return connect()
    except Exception:
        return conn


def minus_iso(now: str, hours: int) -> str:
    """ISO-метка на `hours` часов раньше данной (для периода сводки, D9)."""
    moment = datetime.fromisoformat(now.replace("Z", "+00:00")) - timedelta(hours=hours)
    return moment.strftime("%Y-%m-%dT%H:%M:%SZ")


def insert_item(conn, source_id, url, title, published) -> bool:
    try:
        conn.execute(
            "INSERT INTO items (source_id, url, title, published, fetched_at, url_hash)"
            " VALUES (%s, %s, %s, %s, %s, %s)",
            (source_id, url, title, published or now_iso(), now_iso(), url_hash(url, title)),
        )
        return True
    except (sqlite3.IntegrityError, pg_errors.UniqueViolation):
        return False


def ensure_bootstrap(conn, feed_url) -> int:
    """И1: служебный пользователь chat_id=0 и один захардкоженный RSS-источник."""
    conn.execute(
        "INSERT INTO users (chat_id, created_at) VALUES (%s, %s)"
        " ON CONFLICT (chat_id) DO NOTHING",
        (0, now_iso()),
    )
    conn.execute(
        "INSERT INTO sources (chat_id, kind, url, title, origin, added_at)"
        " VALUES (0, 'rss', %s, 'Bootstrap feed', 'manual', %s)"
        " ON CONFLICT (chat_id, kind, url) DO NOTHING",
        (feed_url, now_iso()),
    )
    conn.commit()
    row = conn.execute(
        "SELECT id FROM sources WHERE chat_id=0 AND kind='rss' AND url=%s", (feed_url,)
    ).fetchone()
    return row[0]


def ensure_user(conn, chat_id) -> None:
    conn.execute(
        "INSERT INTO users (chat_id, created_at) VALUES (%s, %s)"
        " ON CONFLICT (chat_id) DO NOTHING",
        (chat_id, now_iso()),
    )
    conn.commit()


def is_onboarded(conn, chat_id) -> bool:
    row = conn.execute("SELECT onboarded_at FROM users WHERE chat_id=%s", (chat_id,)).fetchone()
    return bool(row and row[0])


def finalize_survey(conn, chat_id, entries, times, mode) -> None:
    """Финализация опроса (D22). replace — удалить прошлые survey-источники;
    add — объединение без дублей по UNIQUE(chat_id, kind, url).
    last_sent_at не трогаем (окно не сбрасывается, сценарии 6.2/6.3)."""
    now = now_iso()
    conn.execute(
        "INSERT INTO users (chat_id, created_at) VALUES (%s, %s)"
        " ON CONFLICT (chat_id) DO NOTHING",
        (chat_id, now),
    )
    if mode == "replace":
        conn.execute("DELETE FROM sources WHERE chat_id=%s AND origin='survey'", (chat_id,))
    executemany(
        conn,
        "INSERT INTO sources (chat_id, kind, url, title, topics, origin, added_at)"
        " VALUES (%s, 'rss', %s, %s, %s, 'survey', %s)"
        " ON CONFLICT (chat_id, kind, url) DO NOTHING",
        [(chat_id, e["url"], e["title"], json.dumps(e.get("topics", [])), now) for e in entries],
    )
    conn.execute(
        "UPDATE users SET send_times=%s, onboarded_at=COALESCE(onboarded_at, %s) WHERE chat_id=%s",
        (json.dumps(times), now, chat_id),
    )
    conn.commit()


def list_sources(conn, chat_id) -> list:
    return conn.execute(
        "SELECT id, title, kind, url, origin, enabled, status, status_msg"
        " FROM sources WHERE chat_id=%s ORDER BY id",
        (chat_id,),
    ).fetchall()


def add_source(conn, chat_id, kind, url, title, origin="manual", topics=None):
    """Добавить источник (FR-04/FR-05). None — уже есть (UNIQUE chat_id,kind,url)."""
    conn.execute(
        "INSERT INTO users (chat_id, created_at) VALUES (%s, %s)"
        " ON CONFLICT (chat_id) DO NOTHING",
        (chat_id, now_iso()),
    )
    try:
        cur = conn.execute(
            "INSERT INTO sources (chat_id, kind, url, title, topics, origin, added_at)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id",
            (chat_id, kind, url, title, json.dumps(topics or []), origin, now_iso()),
        )
    except (sqlite3.IntegrityError, pg_errors.UniqueViolation):
        return None
    new_id = cur.fetchone()[0]  # до commit: sqlite требует дочитать RETURNING-курсор
    conn.commit()
    return new_id


def get_source(conn, source_id):
    return conn.execute(
        "SELECT id, chat_id, kind, url, title, origin, enabled, status, status_msg"
        " FROM sources WHERE id=%s",
        (source_id,),
    ).fetchone()


def set_enabled(conn, source_id, enabled: bool) -> None:
    conn.execute("UPDATE sources SET enabled=%s WHERE id=%s", (1 if enabled else 0, source_id))
    conn.commit()


def delete_source(conn, source_id) -> None:
    """items удаляются каскадом (ON DELETE CASCADE, TC-23)."""
    conn.execute("DELETE FROM sources WHERE id=%s", (source_id,))
    conn.commit()


def enabled_sources(conn, chat_id) -> list:
    """Включённые источники чата всех собираемых типов (И6)."""
    return conn.execute(
        "SELECT id, kind, url, last_post_id FROM sources"
        " WHERE chat_id=%s AND enabled=1 AND kind IN ('rss','html','tgweb','twitter')"
        " ORDER BY id",
        (chat_id,),
    ).fetchall()


def set_last_post_id(conn, source_id, value: int) -> None:
    conn.execute("UPDATE sources SET last_post_id=%s WHERE id=%s", (value, source_id))
    conn.commit()


def set_source_status(conn, source_id, status: str, msg) -> None:
    conn.execute(
        "UPDATE sources SET status=%s, status_msg=%s WHERE id=%s", (status, msg, source_id)
    )
    conn.commit()


def user_settings(conn, chat_id):
    """(row(send_times), источников) или (None, 0), если чат не знаком."""
    row = conn.execute("SELECT send_times FROM users WHERE chat_id=%s", (chat_id,)).fetchone()
    if row is None:
        return None, 0
    count = conn.execute(
        "SELECT COUNT(*) FROM sources WHERE chat_id=%s", (chat_id,)
    ).fetchone()[0]
    return row, count


# --- И4: окно дельты (D26) и расписание (FR-10..FR-12) ------------------------

def pending_items(conn, chat_id, limit=50) -> list:
    """Непотреблённые элементы чата: не входившие ни в одну сводку чата
    (digest_items). published не фильтрует окно (даты фидов ненадёжны,
    D26) — только сортировка, свежие первыми."""
    return conn.execute(
        "SELECT i.id, i.title, i.url FROM items i"
        " JOIN sources s ON s.id = i.source_id"
        " WHERE s.chat_id=%s AND NOT EXISTS ("
        "   SELECT 1 FROM digest_items di JOIN digests d ON d.id=di.digest_id"
        "   WHERE di.item_id=i.id AND d.chat_id=%s)"
        " ORDER BY i.published DESC, i.id DESC LIMIT %s",
        (chat_id, chat_id, limit),
    ).fetchall()


def record_digest(conn, chat_id, message_text, item_ids, now=None) -> int | None:
    """Транзакционная фиксация отправки (план §1.2): digests + digest_items +
    users.last_sent_at одной транзакцией — защита от дублей при catch-up."""
    now = now or now_iso()
    row = conn.execute(
        "SELECT last_sent_at FROM users WHERE chat_id=%s", (chat_id,)
    ).fetchone()
    if row is None:
        return None
    period_from = row[0] or minus_iso(now, 24)  # первая сводка — окно 24 ч (D9)
    try:
        with conn.transaction():
            cur = conn.execute(
                "INSERT INTO digests (chat_id, period_from, period_to, item_count,"
                " message_text, created_at) VALUES (%s, %s, %s, %s, %s, %s)"
                " RETURNING id",
                (chat_id, period_from, now, len(item_ids), message_text, now),
            )
            digest_id = cur.fetchone()[0]
            executemany(
                conn,
                "INSERT INTO digest_items (digest_id, item_id) VALUES (%s, %s)",
                [(digest_id, item_id) for item_id in item_ids],
            )
            conn.execute(
                "UPDATE users SET last_sent_at=%s WHERE chat_id=%s", (now, chat_id)
            )
    except (sqlite3.IntegrityError, pg_errors.UniqueViolation):
        return None
    return digest_id


def set_send_times(conn, chat_id, times) -> None:
    conn.execute(
        "UPDATE users SET send_times=%s WHERE chat_id=%s",
        (json.dumps(sorted(times)), chat_id),
    )
    conn.commit()


def scheduled_users(conn) -> list:
    """Onboarded-чаты для планировщика: расписание, прошлой отправки и
    онбординга (точка отсчёта первой сводки, D9)."""
    return conn.execute(
        "SELECT chat_id, send_times, last_sent_at, onboarded_at"
        " FROM users WHERE onboarded_at IS NOT NULL"
    ).fetchall()


def source_stats(conn, chat_id, hours=24) -> list:
    """Счётчики элементов per источник (FR-20): собрано за последние
    `hours` часов и всего. fetched_at — UTC ISO, сравнение лексикографическое
    (тот же приём, что в cleanup_processed_updates/minus_iso)."""
    return conn.execute(
        "SELECT s.title, s.kind,"
        " (SELECT COUNT(*) FROM items i WHERE i.source_id = s.id"
        "   AND i.fetched_at >= %s) AS fresh,"
        " (SELECT COUNT(*) FROM items i WHERE i.source_id = s.id) AS total"
        " FROM sources s WHERE s.chat_id=%s"
        " ORDER BY fresh DESC, total DESC, s.title",
        (minus_iso(now_iso(), hours), chat_id),
    ).fetchall()


# --- И7: диалоговый режим (R11, D27) -------------------------------------------

def add_chat_message(conn, chat_id, role, text) -> None:
    conn.execute(
        "INSERT INTO chat_history (chat_id, role, text) VALUES (%s, %s, %s)",
        (chat_id, role, text),
    )
    conn.commit()


def chat_history(conn, chat_id, limit=12) -> list[dict]:
    """Последние сообщения диалога этого чата (D27: chat_id), старыми вперёд."""
    rows = conn.execute(
        "SELECT role, text FROM chat_history WHERE chat_id=%s ORDER BY id DESC LIMIT %s",
        (chat_id, limit),
    ).fetchall()
    return [{"role": r["role"], "content": r["text"]} for r in reversed(rows)]


def news_context(conn, chat_id, limit=120) -> str:
    """Контекст ленты чата для диалога: последние заголовки со ссылками."""
    rows = conn.execute(
        "SELECT i.title, i.url FROM items i JOIN sources s ON s.id = i.source_id"
        " WHERE s.chat_id=%s ORDER BY i.id DESC LIMIT %s",
        (chat_id, limit),
    ).fetchall()
    return "\n".join(f"{r['title']} — {r['url']}" for r in rows)
